/**
 * nextjs.ts
 *
 * Generates the complete file tree for a bootstrapped Next.js project.
 * Returns a map of relative file path → UTF-8 file content.
 *
 * The scaffold is intentionally minimal but fully deployable:
 * - vibe.yaml, CLAUDE.md, AGENTS.md — framework manifest and agent instructions
 * - .devcontainer/devcontainer.json — Codespaces support
 * - .github/workflows/*.yml — thin wrappers calling vibe-framework reusable workflows
 * - Dockerfile — standalone Next.js production image (targets Azure Container Apps)
 * - package.json, tsconfig.json, next.config.ts — Next.js app config
 * - src/app/* — minimal app router starter
 *
 * Does NOT generate application business logic — agents write that after bootstrap.
 * Does NOT provision Azure resources — that is handled by configure_cloud.
 *
 * **Adapter support:** Only `"container-app"` is implemented in Phase 1.
 * Callers should check `adapter` before calling this function:
 * if `adapter === "static-web-app"`, `createProject` returns `not_implemented`
 * before reaching this function. The `adapter` param is accepted here so that
 * `vibe.yaml` is generated correctly when static-web-app support is added.
 */
export function generateNextjsScaffold(params: {
  name: string;
  github_owner: string;
  azure_region: string;
  adapter: "container-app" | "static-web-app";
  approvers: string[];
  framework_repo: string; // e.g. "pmermel/vibe-framework"
}): Record<string, string> {
  const { name, github_owner, azure_region, adapter, approvers, framework_repo } = params;
  const registryName = name.replace(/-/g, "") + "acr";

  return {
    "vibe.yaml": vibeYaml({ name, github_owner, azure_region, adapter, approvers, registryName, framework_repo }),
    "CLAUDE.md": claudeMd(name),
    "AGENTS.md": agentsMd(name),
    ".ai/context/AZURE_TARGETS.md": aiContextAzureTargets({ name, github_owner, azure_region, registryName }),
    ".ai/context/STACK_DECISIONS.md": aiContextStackDecisions(name),
    ".devcontainer/devcontainer.json": devcontainer(),
    ".github/workflows/preview.yml": previewWrapper({ name, registryName, framework_repo }),
    ".github/workflows/staging.yml": stagingWrapper({ name, registryName, framework_repo }),
    ".github/workflows/production.yml": productionWrapper({ name, registryName, framework_repo }),
    ".github/workflows/preview-ttl-cleanup.yml": ttlCleanupWrapper({ name, registryName, framework_repo }),
    "Dockerfile": dockerfile(),
    "package.json": packageJson(name),
    "tsconfig.json": tsconfig(),
    "next.config.ts": nextConfig(),
    "src/app/layout.tsx": layout(name),
    "src/app/page.tsx": page(name),
    "src/app/globals.css": globalsCss(),
    "src/__tests__/app.test.ts": appTestPlaceholder(name),
    ".gitignore": gitignore(),
    "README.md": readme({ name, github_owner, framework_repo }),
  };
}

// ---------------------------------------------------------------------------
// Framework manifest
// ---------------------------------------------------------------------------

function vibeYaml(p: {
  name: string;
  github_owner: string;
  azure_region: string;
  adapter: "container-app" | "static-web-app";
  approvers: string[];
  registryName: string;
  framework_repo: string;
}): string {
  const approversList = p.approvers.map((a) => `  - ${a}`).join("\n");
  return `# vibe.yaml — project manifest
# Generated by vibe-framework create_project. Do not edit workflow_refs manually —
# update them via bootstrap automation to keep wrapper workflows in sync.
name: ${p.name}
template: nextjs
adapter: ${p.adapter}
providers:
  - claude
  - codex

branch_policy:
  feature_prefix: feature/
  staging: develop
  production: main

build:
  install: npm ci
  test: npm test
  build: npm run build
  output: .next

deploy:
  preview:
    target: container-app
    max_concurrent: 3
    ttl_hours: 48
  staging:
    target: container-app
  production:
    target: container-app

azure:
  region: ${p.azure_region}
  resource_group: ${p.name}-rg
  registry: ${p.registryName}
  container_app_environment: ${p.name}-env
  preview_app_prefix: ${p.name}-pr
  staging_app: ${p.name}-staging
  production_app: ${p.name}-prod

github:
  repo: ${p.github_owner}/${p.name}
  issues_as_work_queue: true
  workflow_refs:
    preview: ${p.framework_repo}/.github/workflows/reusable-preview.yml@v1
    staging: ${p.framework_repo}/.github/workflows/reusable-staging.yml@v1
    production: ${p.framework_repo}/.github/workflows/reusable-production.yml@v1
    preview_ttl_cleanup: ${p.framework_repo}/.github/workflows/reusable-preview-ttl-cleanup.yml@v1

approvers:
${approversList}
`;
}

// ---------------------------------------------------------------------------
// Agent instruction files
// ---------------------------------------------------------------------------

function claudeMd(name: string): string {
  return `# ${name}

Generated project using [vibe-framework](https://github.com/pmermel/vibe-framework).

## Quick start

\`\`\`bash
npm ci
npm run dev   # http://localhost:3000
npm test
\`\`\`

## Branch model

\`feature/*\` → \`develop\` (staging) → \`main\` (production, requires approval)

Always create a \`feature/<topic>\` branch before making changes. Never commit directly
to \`develop\` or \`main\`.

## Shared context

See \`.ai/context/\` for conventions, stack decisions, and Azure targets.

## Pipeline

Push to a feature branch → GitHub Actions deploys a preview Container App and posts
the URL to the PR. Merge to \`develop\` → staging updates. Approve and merge to
\`main\` → production deploys.
`;
}

function agentsMd(name: string): string {
  return `# ${name}

Generated project using vibe-framework.

## Branch rules
- Always work on \`feature/<topic>\` branches
- Never push directly to \`develop\` or \`main\`
- Open a PR to \`develop\` when the feature is ready

## Commit format
\`\`\`
<type>(<scope>): <short description>
\`\`\`
Types: feat, fix, docs, chore, test, refactor

## Pipeline
- Feature branch PR → preview Container App deployed → URL posted to PR
- Merge to develop → staging updated
- develop → main → production (approval required)

## Context
See \`.ai/context/\` for conventions and stack decisions.
`;
}

// ---------------------------------------------------------------------------
// .ai/context files — shared conventions for both Claude and Codex agents
// ---------------------------------------------------------------------------

function aiContextAzureTargets(p: {
  name: string;
  github_owner: string;
  azure_region: string;
  registryName: string;
}): string {
  return `# Azure Targets — ${p.name}

Project-specific Azure resource names and deployment targets. Agents must use these
values when referencing or provisioning infrastructure for this project. Do not use
framework-level resource names in project commands.

## Resource Group

| Resource | Name |
|---|---|
| Resource group | \`${p.name}-rg\` |
| Region | \`${p.azure_region}\` |

## Container Registry

| Resource | Name |
|---|---|
| Azure Container Registry | \`${p.registryName}\` |
| Login server | \`${p.registryName}.azurecr.io\` |

## Container Apps

| Resource | Name | Notes |
|---|---|---|
| Managed environment | \`${p.name}-env\` | Dedicated to this project |
| Staging Container App | \`${p.name}-staging\` | Updated on push to \`develop\` |
| Production Container App | \`${p.name}-prod\` | Updated on merge to \`main\` (approval required) |
| Preview Container Apps | \`${p.name}-pr-<N>\` | Ephemeral per PR; deleted on close or TTL expiry |

## GitHub Repository

\`${p.github_owner}/${p.name}\`

## OIDC Trust

Each GitHub environment has its own Azure AD app registration and federated credential.
The OIDC token subject must match exactly for Azure login to succeed.

| GitHub Environment | OIDC Subject |
|---|---|
| \`preview\` | \`repo:${p.github_owner}/${p.name}:environment:preview\` |
| \`staging\` | \`repo:${p.github_owner}/${p.name}:environment:staging\` |
| \`production\` | \`repo:${p.github_owner}/${p.name}:environment:production\` |

OIDC federated credentials are provisioned by \`infrastructure/oidc-federated-credential.bicep\`
(called once per environment during \`configure_cloud\`). Secrets \`AZURE_CLIENT_ID\`,
\`AZURE_TENANT_ID\`, and \`AZURE_SUBSCRIPTION_ID\` are stored per GitHub environment.
`;
}

function aiContextStackDecisions(name: string): string {
  return `# Stack Decisions — ${name}

Records the technology choices made at project creation. Update this file when
architectural decisions change.

## Framework

| Layer | Choice | Notes |
|---|---|---|
| Framework | [vibe-framework](https://github.com/pmermel/vibe-framework) | AI-agnostic; supports Claude Code and OpenAI Codex |
| Template | Next.js (App Router) | TypeScript, standalone output for containerization |
| Adapter | container-app | Azure Container Apps deployment model |

## Frontend

| Layer | Choice |
|---|---|
| Runtime | Node.js 20 |
| Framework | Next.js 15 (App Router) |
| Language | TypeScript |
| Styling | None configured — add as needed |

## Infrastructure

| Layer | Choice | Notes |
|---|---|---|
| Hosting | Azure Container Apps | Consumption plan, scale to zero |
| Registry | Azure Container Registry | System-assigned identity for pull auth |
| CI/CD | GitHub Actions | Reusable workflows from vibe-framework |
| Auth | OIDC (no long-lived secrets) | Per-environment federated credentials |
| Secrets | GitHub environment secrets | Scoped to preview / staging / production |

## Branch Model

| Branch | Purpose |
|---|---|
| \`feature/*\` | Feature development — triggers preview deploy |
| \`develop\` | Integration — triggers staging deploy |
| \`main\` | Production — triggers production deploy (approval required) |

## Conventions

- Commit format: Conventional Commits (\`feat\`, \`fix\`, \`docs\`, \`chore\`, etc.)
- Work queue: GitHub Issues
- Context handoff: GitHub state (branch, PR, issue comments) — not session memory
`;
}

// ---------------------------------------------------------------------------
// Devcontainer
// ---------------------------------------------------------------------------

function devcontainer(): string {
  return JSON.stringify(
    {
      name: "vibe-framework project",
      image: "mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye",
      features: {
        "ghcr.io/devcontainers/features/github-cli:1": {},
        "ghcr.io/devcontainers/features/azure-cli:1": {},
      },
      forwardPorts: [3000],
      postCreateCommand: "npm ci",
      remoteEnv: { GH_TOKEN: "${localEnv:GH_TOKEN}" },
      customizations: {
        vscode: {
          extensions: [
            "dbaeumer.vscode-eslint",
            "esbenp.prettier-vscode",
            "ms-azuretools.vscode-azurecontainerapps",
          ],
        },
      },
    },
    null,
    2
  );
}

// ---------------------------------------------------------------------------
// Thin workflow wrappers
// ---------------------------------------------------------------------------

function previewWrapper(p: { name: string; registryName: string; framework_repo: string }): string {
  return `name: Preview
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    # Run on PRs targeting any branch — this includes the initial bootstrap PR
    # (targeting main) as well as ongoing feature PRs (targeting develop).
    branches: ['**']

jobs:
  preview:
    uses: ${p.framework_repo}/.github/workflows/reusable-preview.yml@v1
    with:
      app_name: ${p.name}
      resource_group: ${p.name}-rg
      container_app_environment: ${p.name}-env
      preview_app_prefix: ${p.name}-pr
      registry: ${p.registryName}
      target_port: 3000
    secrets: inherit
`;
}

function stagingWrapper(p: { name: string; registryName: string; framework_repo: string }): string {
  return `name: Staging
on:
  push:
    branches: [develop]

jobs:
  staging:
    uses: ${p.framework_repo}/.github/workflows/reusable-staging.yml@v1
    with:
      app_name: ${p.name}
      resource_group: ${p.name}-rg
      staging_app: ${p.name}-staging
      registry: ${p.registryName}
    secrets: inherit
`;
}

function productionWrapper(p: { name: string; registryName: string; framework_repo: string }): string {
  return `name: Production
on:
  push:
    branches: [main]

jobs:
  production:
    uses: ${p.framework_repo}/.github/workflows/reusable-production.yml@v1
    with:
      app_name: ${p.name}
      resource_group: ${p.name}-rg
      production_app: ${p.name}-prod
      registry: ${p.registryName}
    secrets: inherit
`;
}

function ttlCleanupWrapper(p: { name: string; registryName: string; framework_repo: string }): string {
  return `name: Preview TTL Cleanup
on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours — keeps abandoned previews within the 48-hour TTL

jobs:
  ttl-cleanup:
    uses: ${p.framework_repo}/.github/workflows/reusable-preview-ttl-cleanup.yml@v1
    with:
      resource_group: ${p.name}-rg
      preview_app_prefix: ${p.name}-pr
      registry: ${p.registryName}
      app_name: ${p.name}
      max_age_days: 2
    secrets: inherit
`;
}

// ---------------------------------------------------------------------------
// Next.js application files
// ---------------------------------------------------------------------------

function dockerfile(): string {
  return `# Multi-stage Next.js production image targeting Azure Container Apps.
# Requires next.config.ts to have output: "standalone".

FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
CMD ["node", "server.js"]
`;
}

function packageJson(name: string): string {
  return JSON.stringify(
    {
      name,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        test: "vitest run",
      },
      dependencies: {
        next: "15.1.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
      },
      devDependencies: {
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        typescript: "^5",
        vitest: "^1.2.0",
      },
    },
    null,
    2
  );
}

function tsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2
  );
}

function nextConfig(): string {
  return `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // standalone output required for the production Dockerfile
  output: "standalone",
};

export default nextConfig;
`;
}

function layout(name: string): string {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${name}",
  description: "Generated by vibe-framework",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function page(name: string): string {
  return `export default function Home() {
  return (
    <main style={{ fontFamily: "system-ui, sans-serif", padding: "2rem" }}>
      <h1>${name}</h1>
      <p>Bootstrap scaffold generated by vibe-framework. Start building here.</p>
    </main>
  );
}
`;
}

function globalsCss(): string {
  return `*, *::before, *::after {
  box-sizing: border-box;
}

body {
  margin: 0;
  padding: 0;
}
`;
}

function gitignore(): string {
  return `# dependencies
node_modules/
.pnp
.pnp.js

# Next.js build output
.next/
out/
dist/

# environment
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# misc
.DS_Store
*.pem
npm-debug.log*
`;
}

function appTestPlaceholder(name: string): string {
  return `import { describe, it, expect } from "vitest";

/**
 * Placeholder test suite for ${name}.
 *
 * Replace this file with real unit tests as you build out the application.
 * Run: npm test
 */
describe("${name} — placeholder", () => {
  it("passes as a sanity check", () => {
    expect(true).toBe(true);
  });
});
`;
}

function readme(p: { name: string; github_owner: string; framework_repo: string }): string {
  return `# ${p.name}

Bootstrapped with [vibe-framework](https://github.com/${p.framework_repo}).

## Development

\`\`\`bash
npm ci
npm run dev
\`\`\`

## Deployment

Push a feature branch and open a PR to \`develop\` — a preview environment deploys automatically.
Merge to \`develop\` → staging. Merge to \`main\` → production (requires approval).
`;
}
