/**
 * node-api.ts
 *
 * Generates the complete file tree for a bootstrapped Node API project.
 * Returns a map of relative file path -> UTF-8 file content.
 *
 * The scaffold is intentionally minimal but fully deployable:
 * - vibe.yaml, CLAUDE.md, AGENTS.md — framework manifest and agent instructions
 * - .devcontainer/devcontainer.json — Codespaces support
 * - .github/workflows/*.yml — thin wrappers calling vibe-framework reusable workflows
 * - Dockerfile — TypeScript Node API production image (targets Azure Container Apps)
 * - package.json, tsconfig.json — Node API app config
 * - src/index.ts — minimal Express starter with /health
 *
 * Does NOT generate application business logic — agents write that after bootstrap.
 * Does NOT provision Azure resources — that is handled by configure_cloud.
 *
 * **Adapter support:** Only `"container-app"` is implemented.
 * Callers should check `adapter` before calling this function:
 * if `adapter === "static-web-app"`, `createProject` returns `not_implemented`
 * before reaching this function. The `adapter` param is accepted here so that
 * `vibe.yaml` stays provider-neutral if support expands later.
 */
export function generateNodeApiScaffold(params: {
  name: string;
  github_owner: string;
  azure_region: string;
  adapter: "container-app" | "static-web-app";
  approvers: string[];
  framework_repo: string;
}): Record<string, string> {
  const { name, github_owner, azure_region, adapter, approvers, framework_repo } = params;
  const registryName = name.replace(/-/g, "") + "acr";

  return {
    "vibe.yaml": vibeYaml({ name, github_owner, azure_region, adapter, approvers, registryName, framework_repo }),
    "CLAUDE.md": claudeMd(name),
    "AGENTS.md": agentsMd(name),
    ".ai/context/AZURE_TARGETS.md": aiContextAzureTargets({ name, github_owner, azure_region, registryName }),
    ".ai/context/STACK_DECISIONS.md": aiContextStackDecisions(name),
    ".devcontainer/devcontainer.json": devcontainer(),
    ".github/workflows/preview.yml": previewWrapper({ name, registryName, framework_repo }),
    ".github/workflows/staging.yml": stagingWrapper({ name, registryName, framework_repo }),
    ".github/workflows/production.yml": productionWrapper({ name, registryName, framework_repo }),
    ".github/workflows/preview-ttl-cleanup.yml": ttlCleanupWrapper({ name, registryName, framework_repo }),
    "Dockerfile": dockerfile(),
    "package.json": packageJson(name),
    "tsconfig.json": tsconfig(),
    "src/index.ts": indexTs(name),
    "src/__tests__/app.test.ts": appTestPlaceholder(name),
    ".gitignore": gitignore(),
    "README.md": readme({ name, github_owner, framework_repo }),
  };
}

function vibeYaml(p: {
  name: string;
  github_owner: string;
  azure_region: string;
  adapter: "container-app" | "static-web-app";
  approvers: string[];
  registryName: string;
  framework_repo: string;
}): string {
  const approversList = p.approvers.map((a) => `  - ${a}`).join("\n");
  return `# vibe.yaml — project manifest
# Generated by vibe-framework create_project. Do not edit workflow_refs manually —
# update them via bootstrap automation to keep wrapper workflows in sync.
name: ${p.name}
template: node-api
adapter: ${p.adapter}
providers:
  - claude
  - codex

branch_policy:
  feature_prefix: feature/
  staging: develop
  production: main

build:
  install: npm ci
  test: npm test
  build: npm run build
  output: dist

deploy:
  preview:
    target: container-app
    max_concurrent: 3
    ttl_hours: 48
  staging:
    target: container-app
  production:
    target: container-app

azure:
  region: ${p.azure_region}
  resource_group: ${p.name}-rg
  registry: ${p.registryName}
  container_app_environment: ${p.name}-env
  preview_app_prefix: ${p.name}-pr
  staging_app: ${p.name}-staging
  production_app: ${p.name}-prod

github:
  repo: ${p.github_owner}/${p.name}
  issues_as_work_queue: true
  workflow_refs:
    preview: ${p.framework_repo}/.github/workflows/reusable-preview.yml@v1
    staging: ${p.framework_repo}/.github/workflows/reusable-staging.yml@v1
    production: ${p.framework_repo}/.github/workflows/reusable-production.yml@v1
    preview_ttl_cleanup: ${p.framework_repo}/.github/workflows/reusable-preview-ttl-cleanup.yml@v1

approvers:
${approversList}
`;
}

function claudeMd(name: string): string {
  return `# ${name}

Generated project using [vibe-framework](https://github.com/pmermel/vibe-framework).

## Quick start

\`\`\`bash
npm ci
npm run dev   # http://localhost:8080
npm test
\`\`\`

## Branch model

\`feature/*\` → \`develop\` (staging) → \`main\` (production, requires approval)

Always create a \`feature/<topic>\` branch before making changes. Never commit directly
to \`develop\` or \`main\`.

## Shared context

See \`.ai/context/\` for conventions, stack decisions, and Azure targets.

## Pipeline

Push to a feature branch → GitHub Actions deploys a preview Container App and posts
the URL to the PR. Merge to \`develop\` → staging updates. Approve and merge to
\`main\` → production deploys.
`;
}

function agentsMd(name: string): string {
  return `# ${name}

Generated project using vibe-framework.

## Branch rules
- Always work on \`feature/<topic>\` branches
- Never push directly to \`develop\` or \`main\`
- Open a PR to \`develop\` when the feature is ready

## Commit format
\`\`\`
<type>(<scope>): <short description>
\`\`\`
Types: feat, fix, docs, chore, test, refactor

## Pipeline
- Feature branch PR → preview Container App deployed → URL posted to PR
- Merge to develop → staging updated
- develop → main → production (approval required)

## Context
See \`.ai/context/\` for conventions and stack decisions.
`;
}

function aiContextAzureTargets(p: {
  name: string;
  github_owner: string;
  azure_region: string;
  registryName: string;
}): string {
  return `# Azure Targets — ${p.name}

Project-specific Azure resource names and deployment targets. Agents must use these
values when referencing or provisioning infrastructure for this project. Do not use
framework-level resource names in project commands.

## Resource Group

| Resource | Name |
|---|---|
| Resource group | \`${p.name}-rg\` |
| Region | \`${p.azure_region}\` |

## Container Registry

| Resource | Name |
|---|---|
| Azure Container Registry | \`${p.registryName}\` |
| Login server | \`${p.registryName}.azurecr.io\` |

## Container Apps

| Resource | Name | Notes |
|---|---|---|
| Managed environment | \`${p.name}-env\` | Dedicated to this project |
| Staging Container App | \`${p.name}-staging\` | Updated on push to \`develop\` |
| Production Container App | \`${p.name}-prod\` | Updated on merge to \`main\` (approval required) |
| Preview Container Apps | \`${p.name}-pr-<N>\` | Ephemeral per PR; deleted on close or TTL expiry |

## GitHub Repository

\`${p.github_owner}/${p.name}\`

## OIDC Trust

Each GitHub environment has its own Azure AD app registration and federated credential.
The OIDC token subject must match exactly for Azure login to succeed.

| GitHub Environment | OIDC Subject |
|---|---|
| \`preview\` | \`repo:${p.github_owner}/${p.name}:environment:preview\` |
| \`staging\` | \`repo:${p.github_owner}/${p.name}:environment:staging\` |
| \`production\` | \`repo:${p.github_owner}/${p.name}:environment:production\` |

OIDC federated credentials are provisioned by \`infrastructure/oidc-federated-credential.bicep\`
(called once per environment during \`configure_cloud\`). Secrets \`AZURE_CLIENT_ID\`,
\`AZURE_TENANT_ID\`, and \`AZURE_SUBSCRIPTION_ID\` are stored per GitHub environment.
`;
}

function aiContextStackDecisions(name: string): string {
  return `# Stack Decisions — ${name}

Records the technology choices made at project creation. Update this file when
architectural decisions change.

## Framework

| Layer | Choice | Notes |
|---|---|---|
| Framework | [vibe-framework](https://github.com/pmermel/vibe-framework) | AI-agnostic; supports Claude Code and OpenAI Codex |
| Template | Node API | TypeScript service for Azure Container Apps |
| Adapter | container-app | Azure Container Apps deployment model |

## Backend

| Layer | Choice |
|---|---|
| Runtime | Node.js 20 |
| HTTP framework | Express |
| Language | TypeScript |
| Test runner | Vitest |

## Infrastructure

| Layer | Choice | Notes |
|---|---|---|
| Hosting | Azure Container Apps | Consumption plan, scale to zero |
| Registry | Azure Container Registry | System-assigned identity for pull auth |
| CI/CD | GitHub Actions | Reusable workflows from vibe-framework |
| Auth | OIDC (no long-lived secrets) | Per-environment federated credentials |
| Secrets | GitHub environment secrets | Scoped to preview / staging / production |

## Branch Model

| Branch | Purpose |
|---|---|
| \`feature/*\` | Feature development — triggers preview deploy |
| \`develop\` | Integration — triggers staging deploy |
| \`main\` | Production — triggers production deploy (approval required) |

## Conventions

- Commit format: Conventional Commits (\`feat\`, \`fix\`, \`docs\`, \`chore\`, etc.)
- Work queue: GitHub Issues
- Context handoff: GitHub state (branch, PR, issue comments) — not session memory
`;
}

function devcontainer(): string {
  return JSON.stringify(
    {
      name: "vibe-framework project",
      image: "mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye",
      features: {
        "ghcr.io/devcontainers/features/github-cli:1": {},
        "ghcr.io/devcontainers/features/azure-cli:1": {},
      },
      forwardPorts: [8080],
      postCreateCommand: "npm ci",
      remoteEnv: { GH_TOKEN: "${localEnv:GH_TOKEN}" },
      customizations: {
        vscode: {
          extensions: [
            "dbaeumer.vscode-eslint",
            "esbenp.prettier-vscode",
            "ms-azuretools.vscode-azurecontainerapps",
          ],
        },
      },
    },
    null,
    2
  );
}

function previewWrapper(p: { name: string; registryName: string; framework_repo: string }): string {
  return `name: Preview
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ['**']

jobs:
  preview:
    uses: ${p.framework_repo}/.github/workflows/reusable-preview.yml@v1
    with:
      app_name: ${p.name}
      resource_group: ${p.name}-rg
      container_app_environment: ${p.name}-env
      preview_app_prefix: ${p.name}-pr
      registry: ${p.registryName}
      target_port: 8080
      backend_url: \${{ vars.VIBE_BACKEND_URL }}
    secrets: inherit
`;
}

function stagingWrapper(p: { name: string; registryName: string; framework_repo: string }): string {
  return `name: Staging
on:
  push:
    branches: [develop]

jobs:
  staging:
    uses: ${p.framework_repo}/.github/workflows/reusable-staging.yml@v1
    with:
      app_name: ${p.name}
      resource_group: ${p.name}-rg
      staging_app: ${p.name}-staging
      registry: ${p.registryName}
    secrets: inherit
`;
}

function productionWrapper(p: { name: string; registryName: string; framework_repo: string }): string {
  return `name: Production
on:
  push:
    branches: [main]

jobs:
  production:
    uses: ${p.framework_repo}/.github/workflows/reusable-production.yml@v1
    with:
      app_name: ${p.name}
      resource_group: ${p.name}-rg
      production_app: ${p.name}-prod
      registry: ${p.registryName}
    secrets: inherit
`;
}

function ttlCleanupWrapper(p: { name: string; registryName: string; framework_repo: string }): string {
  return `name: Preview TTL Cleanup
on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  ttl-cleanup:
    uses: ${p.framework_repo}/.github/workflows/reusable-preview-ttl-cleanup.yml@v1
    with:
      resource_group: ${p.name}-rg
      preview_app_prefix: ${p.name}-pr
      registry: ${p.registryName}
      app_name: ${p.name}
      max_age_days: 2
    secrets: inherit
`;
}

function dockerfile(): string {
  return `# Multi-stage TypeScript Node API image targeting Azure Container Apps.

FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8080
EXPOSE 8080
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
CMD ["node", "dist/index.js"]
`;
}

function packageJson(name: string): string {
  return JSON.stringify(
    {
      name,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "tsx watch src/index.ts",
        build: "tsc -p tsconfig.json",
        start: "node dist/index.js",
        test: "vitest run",
      },
      dependencies: {
        express: "^4.21.2",
      },
      devDependencies: {
        "@types/express": "^4.17.21",
        "@types/node": "^20",
        tsx: "^4.19.3",
        typescript: "^5.7.3",
        vitest: "^1.6.1",
      },
    },
    null,
    2
  );
}

function tsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        outDir: "dist",
        rootDir: "src",
        strict: true,
        esModuleInterop: true,
        forceConsistentCasingInFileNames: true,
        skipLibCheck: true,
        types: ["node"],
      },
      include: ["src/**/*.ts"],
      exclude: ["node_modules", "dist"],
    },
    null,
    2
  );
}

function indexTs(name: string): string {
  return `import express from "express";

const app = express();
const port = Number(process.env.PORT ?? 8080);

app.get("/health", (_req, res) => {
  res.json({ status: "ok", service: "${name}" });
});

app.get("/", (_req, res) => {
  res.json({
    service: "${name}",
    message: "Generated by vibe-framework",
  });
});

app.listen(port, () => {
  console.log(\`${name} listening on port \${port}\`);
});
`;
}

function appTestPlaceholder(name: string): string {
  return `import { describe, expect, it } from "vitest";

describe("${name} placeholder", () => {
  it("starts with a passing test placeholder", () => {
    expect(true).toBe(true);
  });
});
`;
}

function gitignore(): string {
  return `node_modules
dist
.env
.env.*
coverage
`;
}

function readme(p: { name: string; github_owner: string; framework_repo: string }): string {
  return `# ${p.name}

Generated by [vibe-framework](https://github.com/${p.framework_repo}).

## Local development

\`\`\`bash
npm ci
npm run dev
\`\`\`

The API listens on \`http://localhost:8080\`.

## Tests

\`\`\`bash
npm test
\`\`\`

## Deployment model

- Preview: PR-based Azure Container Apps preview environment
- Staging: deploy from \`develop\`
- Production: deploy from \`main\` after approval

## Repository

GitHub repo: \`${p.github_owner}/${p.name}\`
`;
}
