/**
 * react-vite.ts
 *
 * Generates the complete file tree for a bootstrapped React/Vite project
 * targeting Azure Static Web Apps. Returns a map of relative file path ->
 * UTF-8 file content.
 *
 * The scaffold is intentionally minimal but fully deployable:
 * - vibe.yaml, CLAUDE.md, AGENTS.md — framework manifest and agent instructions
 * - .ai/context/ — Azure targets and stack decisions (SWA-specific, no Container Registry)
 * - .devcontainer/devcontainer.json — Codespaces support (port 5173 for Vite)
 * - .github/workflows/*.yml — thin wrapper workflows calling pinned reusable SWA framework workflows
 * - index.html, vite.config.ts, tsconfig.json — Vite project config
 * - src/main.tsx, src/App.tsx, src/index.css — minimal React starter
 * - src/__tests__/App.test.ts — vitest placeholder
 * - package.json — React 18 + Vite 5 + TypeScript + vitest
 *
 * Does NOT generate application business logic — agents write that after bootstrap.
 * Does NOT provision Azure resources — that is handled by configure_cloud.
 * Does NOT generate a Dockerfile or container-related workflows — SWA deploys
 * static assets; there is no container runtime involved.
 *
 * **Adapter support:** Only `"static-web-app"` is valid for this scaffold.
 * The caller (`createProject`) enforces template + adapter compatibility before
 * reaching this function.
 */
export function generateReactViteScaffold(params: {
  name: string;
  github_owner: string;
  azure_region: string;
  adapter: "container-app" | "static-web-app";
  approvers: string[];
  framework_repo: string;
}): Record<string, string> {
  const { name, github_owner, azure_region, approvers, framework_repo } = params;

  return {
    "vibe.yaml": vibeYaml({ name, github_owner, azure_region, approvers, framework_repo }),
    "CLAUDE.md": claudeMd(name),
    "AGENTS.md": agentsMd(name),
    ".ai/context/AZURE_TARGETS.md": aiContextAzureTargets({ name, github_owner, azure_region }),
    ".ai/context/STACK_DECISIONS.md": aiContextStackDecisions(name),
    ".devcontainer/devcontainer.json": devcontainer(),
    ".github/workflows/preview.yml": previewWrapper({ name, framework_repo }),
    ".github/workflows/staging.yml": stagingWrapper({ name, framework_repo }),
    ".github/workflows/production.yml": productionWrapper({ name, framework_repo }),
    "index.html": indexHtml(name),
    "vite.config.ts": viteConfig(),
    "src/main.tsx": mainTsx(),
    "src/App.tsx": appTsx(name),
    "src/index.css": indexCss(),
    "src/__tests__/App.test.ts": appTestPlaceholder(name),
    "tsconfig.json": tsconfig(),
    "package.json": packageJson(name),
    ".gitignore": gitignore(),
    "README.md": readme({ name, github_owner, framework_repo }),
  };
}

function vibeYaml(p: {
  name: string;
  github_owner: string;
  azure_region: string;
  approvers: string[];
  framework_repo: string;
}): string {
  const approversList = p.approvers.map((a) => `  - ${a}`).join("\n");
  return `# vibe.yaml — project manifest
# Generated by vibe-framework create_project. Do not edit manually.
name: ${p.name}
template: react-vite
adapter: static-web-app
providers:
  - claude
  - codex

branch_policy:
  feature_prefix: feature/
  staging: develop
  production: main

build:
  install: npm install
  test: npm test
  build: npm run build
  output: dist

deploy:
  preview:
    target: static-web-app
  staging:
    target: static-web-app
  production:
    target: static-web-app

azure:
  region: ${p.azure_region}
  resource_group: ${p.name}-rg
  static_web_app: ${p.name}-swa

github:
  repo: ${p.github_owner}/${p.name}
  issues_as_work_queue: true
  workflow_refs:
    preview: ${p.framework_repo}/.github/workflows/reusable-swa-preview.yml@v1
    staging: ${p.framework_repo}/.github/workflows/reusable-swa-staging.yml@v1
    production: ${p.framework_repo}/.github/workflows/reusable-swa-production.yml@v1

approvers:
${approversList}
`;
}

function claudeMd(name: string): string {
  return `# ${name}

Generated project using [vibe-framework](https://github.com/pmermel/vibe-framework).

## Quick start

\`\`\`bash
npm install
npm run dev   # http://localhost:5173
npm test
\`\`\`

## Branch model

\`feature/*\` → \`develop\` (staging) → \`main\` (production, requires approval)

Always create a \`feature/<topic>\` branch before making changes. Never commit directly
to \`develop\` or \`main\`.

## Shared context

See \`.ai/context/\` for conventions, stack decisions, and Azure targets.

## Pipeline

Push to a feature branch → GitHub Actions deploys a preview to Azure Static Web Apps and
posts the URL to the PR. Merge to \`develop\` → staging updates. Approve and merge to
\`main\` → production deploys.
`;
}

function agentsMd(name: string): string {
  return `# ${name}

Generated project using vibe-framework.

## Branch rules
- Always work on \`feature/<topic>\` branches
- Never push directly to \`develop\` or \`main\`
- Open a PR to \`develop\` when the feature is ready

## Commit format
\`\`\`
<type>(<scope>): <short description>
\`\`\`
Types: feat, fix, docs, chore, test, refactor

## Pipeline
- Feature branch PR → preview Static Web App environment deployed → URL posted to PR
- Merge to develop → staging updated
- develop → main → production (approval required)

## Context
See \`.ai/context/\` for conventions and stack decisions.
`;
}

function aiContextAzureTargets(p: {
  name: string;
  github_owner: string;
  azure_region: string;
}): string {
  return `# Azure Targets — ${p.name}

Project-specific Azure resource names and deployment targets. Agents must use these
values when referencing or provisioning infrastructure for this project. Do not use
framework-level resource names in project commands.

## Resource Group

| Resource | Name |
|---|---|
| Resource group | \`${p.name}-rg\` |
| Region | \`${p.azure_region}\` |

## Static Web App

| Resource | Name | Notes |
|---|---|---|
| Static Web App | \`${p.name}-swa\` | Hosts all environments (production, staging, preview) |

No Container Registry or Container Apps are used for this project. Deployment is
handled via the reusable SWA framework workflows (\`reusable-swa-*.yml\`), which fetch
the SWA deployment token at runtime via OIDC login and \`az staticwebapp secrets list\`.
No long-lived deployment token secret is stored in the repository.

## Environments

| Environment | Mechanism |
|---|---|
| Production | Main branch → SWA production slot |
| Staging | \`develop\` branch → SWA named environment \`staging\` |
| Preview | PR-based ephemeral SWA environment (auto-closed on PR close) |

## GitHub Repository

\`${p.github_owner}/${p.name}\`

## OIDC Trust

Each GitHub environment has its own Azure AD app registration and federated credential.
The OIDC token subject must match exactly for Azure login to succeed.

| GitHub Environment | OIDC Subject |
|---|---|
| \`preview\` | \`repo:${p.github_owner}/${p.name}:environment:preview\` |
| \`staging\` | \`repo:${p.github_owner}/${p.name}:environment:staging\` |
| \`production\` | \`repo:${p.github_owner}/${p.name}:environment:production\` |

OIDC federated credentials are provisioned by \`configure_cloud\` during bootstrap.
Secrets \`AZURE_CLIENT_ID\`, \`AZURE_TENANT_ID\`, and \`AZURE_SUBSCRIPTION_ID\` are stored
per GitHub environment. The SWA deployment token is fetched at runtime by the
\`reusable-swa-*.yml\` workflows via \`az staticwebapp secrets list\` — not stored as a secret.
`;
}

function aiContextStackDecisions(name: string): string {
  return `# Stack Decisions — ${name}

Records the technology choices made at project creation. Update this file when
architectural decisions change.

## Framework

| Layer | Choice | Notes |
|---|---|---|
| Framework | [vibe-framework](https://github.com/pmermel/vibe-framework) | AI-agnostic; supports Claude Code and OpenAI Codex |
| Template | React/Vite | TypeScript SPA for Azure Static Web Apps |
| Adapter | static-web-app | Azure Static Web Apps deployment model |

## Frontend

| Layer | Choice |
|---|---|
| Runtime | Browser (static assets) |
| UI framework | React 18 |
| Build tool | Vite 5 |
| Language | TypeScript |
| Test runner | Vitest |

## Infrastructure

| Layer | Choice | Notes |
|---|---|---|
| Hosting | Azure Static Web Apps | Standard tier; supports staging + preview environments |
| CI/CD | GitHub Actions | Thin wrappers calling pinned reusable SWA framework workflows |
| Auth | OIDC (no long-lived secrets) | Per-environment federated credentials; SWA token fetched at runtime |
| Secrets | GitHub environment secrets only | OIDC creds per env; no stored SWA deployment token |

## Branch Model

| Branch | Purpose |
|---|---|
| \`feature/*\` | Feature development — triggers preview SWA deploy |
| \`develop\` | Integration — triggers staging SWA deploy |
| \`main\` | Production — triggers production SWA deploy (approval required) |

## Conventions

- Commit format: Conventional Commits (\`feat\`, \`fix\`, \`docs\`, \`chore\`, etc.)
- Work queue: GitHub Issues
- Context handoff: GitHub state (branch, PR, issue comments) — not session memory
`;
}

function devcontainer(): string {
  return JSON.stringify(
    {
      name: "vibe-framework project",
      image: "mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye",
      features: {
        "ghcr.io/devcontainers/features/github-cli:1": {},
        "ghcr.io/devcontainers/features/azure-cli:1": {},
      },
      forwardPorts: [5173],
      postCreateCommand: "npm install",
      remoteEnv: { GH_TOKEN: "${localEnv:GH_TOKEN}" },
      customizations: {
        vscode: {
          extensions: [
            "dbaeumer.vscode-eslint",
            "esbenp.prettier-vscode",
            "ms-azuretools.vscode-azurestaticwebapps",
          ],
        },
      },
    },
    null,
    2
  );
}

function previewWrapper(p: { name: string; framework_repo: string }): string {
  return `name: Preview
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ['**']

jobs:
  preview:
    uses: ${p.framework_repo}/.github/workflows/reusable-swa-preview.yml@v1
    with:
      app_name: ${p.name}
      resource_group: ${p.name}-rg
      swa_name: ${p.name}-swa
      install_command: npm install
      build_command: npm run build
    secrets: inherit
`;
}

function stagingWrapper(p: { name: string; framework_repo: string }): string {
  return `name: Staging
on:
  push:
    branches: [develop]

jobs:
  staging:
    uses: ${p.framework_repo}/.github/workflows/reusable-swa-staging.yml@v1
    with:
      app_name: ${p.name}
      resource_group: ${p.name}-rg
      swa_name: ${p.name}-swa
      install_command: npm install
      build_command: npm run build
    secrets: inherit
`;
}

function productionWrapper(p: { name: string; framework_repo: string }): string {
  return `name: Production
on:
  push:
    branches: [main]

jobs:
  production:
    uses: ${p.framework_repo}/.github/workflows/reusable-swa-production.yml@v1
    with:
      app_name: ${p.name}
      resource_group: ${p.name}-rg
      swa_name: ${p.name}-swa
      install_command: npm install
      build_command: npm run build
    secrets: inherit
`;
}

function indexHtml(name: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

function viteConfig(): string {
  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
});
`;
}

function mainTsx(): string {
  return `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.tsx";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;
}

function appTsx(name: string): string {
  return `function App() {
  return (
    <div>
      <h1>${name}</h1>
      <p>Generated by vibe-framework. Start building here.</p>
    </div>
  );
}

export default App;
`;
}

function indexCss(): string {
  return `*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: system-ui, -apple-system, sans-serif;
  line-height: 1.5;
}
`;
}

function appTestPlaceholder(name: string): string {
  return `import { describe, expect, it } from "vitest";

describe("${name} placeholder", () => {
  it("starts with a passing test placeholder", () => {
    expect(true).toBe(true);
  });
});
`;
}

function tsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        useDefineForClassFields: true,
        lib: ["ES2020", "DOM", "DOM.Iterable"],
        module: "ESNext",
        skipLibCheck: true,
        moduleResolution: "bundler",
        allowImportingTsExtensions: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        jsx: "react-jsx",
        strict: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noFallthroughCasesInSwitch: true,
      },
      include: ["src"],
      references: [{ path: "./tsconfig.node.json" }],
    },
    null,
    2
  );
}

function packageJson(name: string): string {
  return JSON.stringify(
    {
      name,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview",
        test: "vitest run",
      },
      dependencies: {
        react: "^18.3.1",
        "react-dom": "^18.3.1",
      },
      devDependencies: {
        "@types/react": "^18.3.5",
        "@types/react-dom": "^18.3.0",
        "@vitejs/plugin-react": "^4.3.1",
        typescript: "^5.5.3",
        vite: "^5.4.2",
        vitest: "^1.6.1",
      },
    },
    null,
    2
  );
}

function gitignore(): string {
  return `node_modules
dist
.env
.env.*
coverage
`;
}

function readme(p: { name: string; github_owner: string; framework_repo: string }): string {
  return `# ${p.name}

Generated by [vibe-framework](https://github.com/${p.framework_repo}).

## Local development

\`\`\`bash
npm install
npm run dev
\`\`\`

The app runs at \`http://localhost:5173\`.

## Tests

\`\`\`bash
npm test
\`\`\`

## Deployment model

- Preview: PR-based Azure Static Web Apps preview environment
- Staging: deploy from \`develop\`
- Production: deploy from \`main\` after approval

## Repository

GitHub repo: \`${p.github_owner}/${p.name}\`
`;
}
