#!/usr/bin/env bash
# setup-azure.sh
# Provisions the vibe-framework backend's Azure infrastructure.
# Called by init.sh — do not run directly unless you know what you are doing.
#
# Required env vars (set by init.sh or passed directly):
#   AZURE_SUBSCRIPTION_ID  — Azure subscription to deploy into
#   AZURE_REGION           — Azure region (e.g. eastus2)
#   RESOURCE_GROUP         — Resource group name (e.g. vibe-framework-rg)
#   REGISTRY_NAME          — ACR name (globally unique, alphanumeric, 5-50 chars)
#   BACKEND_APP_NAME       — Container App name (default: vibe-backend)
#
# Writes outputs to .vibe-env in the repo root for init.sh to source.
set -euo pipefail

: "${AZURE_SUBSCRIPTION_ID:?AZURE_SUBSCRIPTION_ID is required}"
: "${AZURE_REGION:?AZURE_REGION is required}"
: "${RESOURCE_GROUP:?RESOURCE_GROUP is required}"
: "${REGISTRY_NAME:?REGISTRY_NAME is required}"
: "${BACKEND_APP_NAME:=${BACKEND_APP_NAME:-vibe-backend}}"

# Resolve repo root (this script lives at scripts/setup-azure.sh)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "→ Setting active Azure subscription to $AZURE_SUBSCRIPTION_ID"
az account set --subscription "$AZURE_SUBSCRIPTION_ID"

echo "→ Creating resource group $RESOURCE_GROUP in $AZURE_REGION"
az group create \
  --name "$RESOURCE_GROUP" \
  --location "$AZURE_REGION" \
  --output none

echo "→ Deploying framework-env.bicep to resource group $RESOURCE_GROUP"
DEPLOYMENT_OUTPUT=$(az deployment group create \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$REPO_ROOT/infrastructure/framework-env.bicep" \
  --parameters \
      location="$AZURE_REGION" \
      backendAppName="$BACKEND_APP_NAME" \
      registryName="$REGISTRY_NAME" \
  --query "properties.outputs" \
  --output json)

echo "→ Capturing deployment outputs"
BACKEND_URL=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.backendUrl.value')
ACR_LOGIN_SERVER=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.acrLoginServer.value')
BACKEND_PRINCIPAL_ID=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.backendPrincipalId.value')

echo "→ Writing outputs to $REPO_ROOT/.vibe-env"
cat > "$REPO_ROOT/.vibe-env" <<EOF
# Generated by scripts/setup-azure.sh — do not edit manually.
# Source this file to pick up Azure deployment outputs:
#   . .vibe-env
export BACKEND_URL="$BACKEND_URL"
export ACR_LOGIN_SERVER="$ACR_LOGIN_SERVER"
export BACKEND_PRINCIPAL_ID="$BACKEND_PRINCIPAL_ID"
export RESOURCE_GROUP="$RESOURCE_GROUP"
export BACKEND_APP_NAME="$BACKEND_APP_NAME"
export REGISTRY_NAME="$REGISTRY_NAME"
EOF

echo "→ Building and pushing backend image to ACR ($REGISTRY_NAME)"
# az acr build runs entirely in Azure — no local Docker daemon required.
# Context is the repo root so the Dockerfile can reference backend/ and infrastructure/.
az acr build \
  --registry "$REGISTRY_NAME" \
  --image "vibe-backend:latest" \
  --file "$REPO_ROOT/backend/Dockerfile" \
  "$REPO_ROOT"

echo "→ Capturing storage account name from deployment outputs"
STORAGE_ACCOUNT_NAME=$(az deployment group show \
  --resource-group "$RESOURCE_GROUP" \
  --name "framework-env-deploy" \
  --query "properties.outputs.storageAccountName.value" -o tsv)

echo "→ Updating Container App to use real image"
az containerapp update \
  --name "$BACKEND_APP_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --image "$REGISTRY_NAME.azurecr.io/vibe-backend:latest" \
  --registry-server "$REGISTRY_NAME.azurecr.io" \
  --registry-identity system \
  --output none

echo "→ Wiring storage account name and backend URL to Container App env vars"
az containerapp update \
  --name "${BACKEND_APP_NAME:-vibe-backend}" \
  --resource-group "$RESOURCE_GROUP" \
  --set-env-vars \
    "AZURE_STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME" \
    "BACKEND_URL=$BACKEND_URL" \
  --output none

echo "→ Azure provisioning complete"
echo "   Backend URL:        $BACKEND_URL"
echo "   ACR login server:   $ACR_LOGIN_SERVER"
echo "   Storage account:    $STORAGE_ACCOUNT_NAME"
