#!/usr/bin/env bash
# setup-azure.sh
# Provisions the vibe-framework backend's Azure infrastructure.
# Called by init.sh — do not run directly unless you know what you are doing.
#
# Required env vars (set by init.sh or passed directly):
#   AZURE_SUBSCRIPTION_ID  — Azure subscription to deploy into
#   AZURE_REGION           — Azure region (e.g. eastus2)
#   RESOURCE_GROUP         — Resource group name (e.g. vibe-framework-rg)
#   REGISTRY_NAME          — ACR name (globally unique, alphanumeric, 5-50 chars)
#   BACKEND_APP_NAME       — Container App name (default: vibe-backend)
#
# Writes outputs to .vibe-env in the repo root for init.sh to source.
set -euo pipefail

: "${AZURE_SUBSCRIPTION_ID:?AZURE_SUBSCRIPTION_ID is required}"
: "${AZURE_REGION:?AZURE_REGION is required}"
: "${RESOURCE_GROUP:?RESOURCE_GROUP is required}"
: "${REGISTRY_NAME:?REGISTRY_NAME is required}"
: "${BACKEND_APP_NAME:=${BACKEND_APP_NAME:-vibe-backend}}"

# Resolve repo root (this script lives at scripts/setup-azure.sh)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "→ Setting active Azure subscription to $AZURE_SUBSCRIPTION_ID"
az account set --subscription "$AZURE_SUBSCRIPTION_ID"

echo "→ Creating resource group $RESOURCE_GROUP in $AZURE_REGION"
az group create \
  --name "$RESOURCE_GROUP" \
  --location "$AZURE_REGION" \
  --output none

echo "→ Deploying framework-env.bicep to resource group $RESOURCE_GROUP"
DEPLOYMENT_OUTPUT=$(az deployment group create \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$REPO_ROOT/infrastructure/framework-env.bicep" \
  --parameters \
      location="$AZURE_REGION" \
      backendAppName="$BACKEND_APP_NAME" \
      registryName="$REGISTRY_NAME" \
  --query "properties.outputs" \
  --output json)

echo "→ Capturing deployment outputs"
BACKEND_URL=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.backendUrl.value')
ACR_LOGIN_SERVER=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.acrLoginServer.value')
BACKEND_PRINCIPAL_ID=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.backendPrincipalId.value')

echo "→ Writing outputs to $REPO_ROOT/.vibe-env"
cat > "$REPO_ROOT/.vibe-env" <<EOF
# Generated by scripts/setup-azure.sh — do not edit manually.
# Source this file to pick up Azure deployment outputs:
#   . .vibe-env
export BACKEND_URL="$BACKEND_URL"
export ACR_LOGIN_SERVER="$ACR_LOGIN_SERVER"
export BACKEND_PRINCIPAL_ID="$BACKEND_PRINCIPAL_ID"
export RESOURCE_GROUP="$RESOURCE_GROUP"
export BACKEND_APP_NAME="$BACKEND_APP_NAME"
export REGISTRY_NAME="$REGISTRY_NAME"
EOF

echo "→ Staging infrastructure files into backend/ for Docker build context"
# The Dockerfile build context is backend/. Infrastructure ARM templates live at
# the repo root and cannot be referenced via ../infrastructure/ inside Docker.
# We pre-stage them so the Dockerfile can COPY infrastructure/ explicitly.
mkdir -p "$REPO_ROOT/backend/infrastructure"
cp "$REPO_ROOT/infrastructure/container-apps-env.json" "$REPO_ROOT/backend/infrastructure/"

echo "→ Building and pushing backend image to ACR ($REGISTRY_NAME)"
# az acr build runs entirely in Azure — no local Docker daemon required.
# Context is backend/ — Dockerfile references only files within that directory.
az acr build \
  --registry "$REGISTRY_NAME" \
  --image "vibe-backend:latest" \
  --file "$REPO_ROOT/backend/Dockerfile" \
  "$REPO_ROOT/backend"

echo "→ Capturing storage account name from deployment outputs"
STORAGE_ACCOUNT_NAME=$(az deployment group show \
  --resource-group "$RESOURCE_GROUP" \
  --name "framework-env-deploy" \
  --query "properties.outputs.storageAccountName.value" -o tsv)

echo "→ Updating Container App to use real image (with RBAC propagation retry)"
# AcrPull role assignment was created during Bicep deployment but Azure RBAC
# propagation can take several minutes. We retry the containerapp update with
# exponential backoff so bootstrap remains reliable rather than timing-dependent.
ACR_UPDATE_OK=false
for attempt in 1 2 3 4 5; do
  echo "   Attempt $attempt/5: updating Container App image and registry config"
  if az containerapp update \
    --name "$BACKEND_APP_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --image "$REGISTRY_NAME.azurecr.io/vibe-backend:latest" \
    --registry-server "$REGISTRY_NAME.azurecr.io" \
    --registry-identity system \
    --output none 2>&1; then
    ACR_UPDATE_OK=true
    break
  fi
  if [[ $attempt -lt 5 ]]; then
    WAIT=$(( attempt * 30 ))
    echo "   Update failed — waiting ${WAIT}s for RBAC propagation before retry"
    sleep "$WAIT"
  fi
done

if [[ "$ACR_UPDATE_OK" != "true" ]]; then
  echo ""
  echo "ERROR: Container App image update failed after 5 attempts."
  echo "       AcrPull role may not have propagated. Wait a few minutes and re-run:"
  echo "         az containerapp update \\"
  echo "           --name $BACKEND_APP_NAME \\"
  echo "           --resource-group $RESOURCE_GROUP \\"
  echo "           --image $REGISTRY_NAME.azurecr.io/vibe-backend:latest \\"
  echo "           --registry-server $REGISTRY_NAME.azurecr.io \\"
  echo "           --registry-identity system"
  exit 1
fi

echo "→ Wiring storage account name and backend URL to Container App env vars"
az containerapp update \
  --name "${BACKEND_APP_NAME:-vibe-backend}" \
  --resource-group "$RESOURCE_GROUP" \
  --set-env-vars \
    "AZURE_STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME" \
    "BACKEND_URL=$BACKEND_URL" \
  --output none

echo "→ Generating MCP API key and storing as Container App secret"
MCP_API_KEY=$(openssl rand -hex 32)
az containerapp secret set \
  --name "${BACKEND_APP_NAME:-vibe-backend}" \
  --resource-group "$RESOURCE_GROUP" \
  --secrets "mcp-api-key=$MCP_API_KEY" \
  --output none

# Wire the secret to the MCP_API_KEY environment variable so the backend can
# read it from process.env. Container Apps secrets are not auto-injected —
# they must be explicitly referenced via secretRef.
az containerapp update \
  --name "${BACKEND_APP_NAME:-vibe-backend}" \
  --resource-group "$RESOURCE_GROUP" \
  --set-env-vars "MCP_API_KEY=secretref:mcp-api-key" \
  --output none

# Append MCP_API_KEY to .vibe-env so init.sh and setup-github.sh can read it.
cat >> "$REPO_ROOT/.vibe-env" <<ENVEOF
export MCP_API_KEY="$MCP_API_KEY"
ENVEOF

echo "→ Azure provisioning complete"
echo "   Backend URL:        $BACKEND_URL"
echo "   ACR login server:   $ACR_LOGIN_SERVER"
echo "   Storage account:    $STORAGE_ACCOUNT_NAME"
echo "   MCP API key:        (written to .vibe-env)"
